(in-package :structural-editing-mcp-tests)

(deftest test-conditions
         (ok (signals (string-to-sexp "(a b c") 'sexp-parse-error))
         (ok (signals (string-to-sexp "(a b c]") 'sexp-parse-error))
         (ok (signals (insert-expression (string-to-sexp "(a b c)") '(0) 1 "")
                      'sexp-parse-error))
         (ok (signals (overwrite-expression (string-to-sexp "(a b c)") '(0 1) "")
                      'sexp-parse-error))
         (ok (signals (update-node-at-path (string-to-sexp "(a b c)") '(0 99) #'identity)
                      'invalid-path-error))
         (ok (signals (merge-nodes (string-to-sexp "((a) ((b)))") '(0 0) '(0 1 0))
                      'invalid-path-error))
         (let* ((ctx (make-workspace-context)))
           (setf (structural-editing-mcp.workspace::workspace-context-tree ctx) nil)
           (with-workspace-context (ctx)
                                   (ok (signals (write-workspace) 'workspace-error)))))
