(defpackage :structural-editing-mcp.analysis
  (:use :cl
        :alexandria
        :trivia
        :structural-editing-mcp.tree
        :structural-editing-mcp.parser)
  (:import-from :serapeum :trim-whitespace :ellipsize :filter-map :fmt :string-join :string-prefix-p)
  (:export :variable-node-p
           :match-pattern
           :instantiate-pattern
           :search-ast
           :find-pattern-matches
           :*anti-pattern-rules*
           :lint-finding
           :lint-rule
           :make-lint-rule
           :rule-applicable-p
           :check-rule
           :rule-id
           :make-lint-finding
           :lint-finding-rule
           :lint-finding-path
           :lint-finding-message
           :lint-finding-severity
           :lint-finding-suggested-fix
           :lint-node
           :if-form-p
           :not-form-cond
           :progn-form-body-nodes
           :lint-ast
           :format-lint-findings
           :complexity-metrics
           :make-complexity-metrics
           :complexity-metrics-name
           :complexity-metrics-kind
           :complexity-metrics-path
           :complexity-metrics-cyclomatic-complexity
           :complexity-metrics-max-nesting-depth
           :complexity-metrics-form-count
           :complexity-metrics-recommendations
           :form-definition-info
           :compute-branch-complexity
           :compute-nesting-depth
           :count-ast-nodes
           :analyze-form-complexity
           :analyze-complexity
           :format-complexity-report
           :duplicate-group
           :make-duplicate-group
           :duplicate-group-code-snippet
           :duplicate-group-occurrence-count
           :duplicate-group-paths
           :duplicate-group-node-count
           :duplicate-group-depth
           :duplicate-group-recommendation
           :canonicalize-subtree
           :find-duplicate-subtrees
           :format-duplicate-report
           :binding-finding
           :make-binding-finding
           :binding-finding-kind
           :binding-finding-variable-name
           :binding-finding-path
           :binding-finding-scope-kind
           :binding-finding-outer-path
           :binding-finding-message
           :binding-finding-recommendation
           :vector-binding-dialect-p
           :lisp-1-dialect-p
           :analyze-bindings
           :format-unused-bindings
           :format-shadowed-bindings
           :format-binding-report
           :refactoring-suggestion
           :make-refactoring-suggestion
           :refactoring-suggestion-category
           :refactoring-suggestion-priority
           :refactoring-suggestion-path
           :refactoring-suggestion-description
           :refactoring-suggestion-recommended-tool
           :refactoring-suggestion-action-plan
           :suggest-refactorings
           :format-refactoring-suggestions)
  (:documentation "Static analysis, pattern matching, structural search, and linting."))
